// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[] = "146f1188-40f5-4db7-b83e-95a217ff9b0e";

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)


CloudPercentage luftfuktsensor;
float temperatur;
float LuftFukt;
int jordfukt;
int lys;
int CO2;

void initProperties(){
  
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(LuftFukt, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperatur, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(CO2, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(lys, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(jordfukt, READ, 1 * SECONDS, NULL);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
